//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int ID_currency { get; set; }
        public System.DateTime Date { get; set; }
        public double USD { get; set; }
        public double EUR { get; set; }
        public double RUB { get; set; }
    }
}
