//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int ID_flight { get; set; }
        public int Departure_city_id { get; set; }
        public int Day_of_week { get; set; }
        public System.DateTime Departure_date { get; set; }
        public int Flight_number { get; set; }
        public int Flight_type { get; set; }
        public string Departure_time { get; set; }
        public System.TimeSpan Arrival_time1 { get; set; }
        public System.TimeSpan Arrival_time2 { get; set; }
        public int Total_place_number { get; set; }
        public int Free_place_number1 { get; set; }
        public int Free_place_numbe2 { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
    }
}
