//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Present
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public List_Present()
        {
            this.Hotels = new HashSet<Hotel>();
        }
    
        public int ID_List_Present { get; set; }
        public bool Present_Bar { get; set; }
        public bool Present_Beach { get; set; }
        public bool Present_WiFi { get; set; }
        public bool Present_Buffet { get; set; }
        public bool Present_Swimming_Pool { get; set; }
        public bool Present_Swimming_Sauna { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotels { get; set; }
    }
}
