//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Include
    {
        public int ID_List_Include { get; set; }
        public bool Tour_Include_Flight { get; set; }
        public bool Tour_Include_Visa { get; set; }
        public bool Tour_Include_Hotel { get; set; }
        public bool Tour_Include_Excursion { get; set; }
        public bool Tour_Include_Entertaiments { get; set; }
    }
}
