//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int ID_tour { get; set; }
        public int Departure_city_id { get; set; }
        public int Arrival_country_id { get; set; }
        public System.DateTime Departure_date { get; set; }
        public System.TimeSpan Tour_duration { get; set; }
        public int Flight_id { get; set; }
        public int Price { get; set; }
        public int List_include_id { get; set; }
        public string Tour_type { get; set; }
        public string Tour_description { get; set; }
        public int Comission { get; set; }
        public int Tour_company_id { get; set; }
        public int Resort_id { get; set; }
        public int Hotel_id { get; set; }
    
        public virtual City City { get; set; }
        public virtual Company Company { get; set; }
        public virtual Country Country { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual List_Include List_Include { get; set; }
        public virtual Resort Resort { get; set; }
        public string PriceRub => Price + " руб.";
        public string HashedID => "Тур #" + ID_tour + " ";
        public string FormattedDuration
        {
            get
            {
                int hours = Tour_duration.Hours;
                int minutes = Tour_duration.Minutes;

                if (minutes == 0)
                    return $"{hours}ч";
                else
                    return $"{hours}ч. {minutes} мин.";
            }
        }
    }
}
